const Discord = require('discord.js');
const keygen = require('keygenerator');
const isAdmin = require('./../functions/admin/isAdmin');
const isEmpty = require('./../functions/utils/isEmpty');
const convertDate = require('./../functions/time/convertDate');
const poolQuery = require('./../functions/database/poolQuery');
const config = require('./../../config.json')
module.exports = async function(bot, message, args) {
    if (isAdmin(message.author.id)) {
        if (!isEmpty(args)) {
            function splitString (string, size) {
                var re = new RegExp('.{1,' + size + '}', 'g');
                return string.match(re);
            }

            const key = splitString(keygen._({forceUppercase: true, length: 30}), 6).join('-');
            var receiver = args[0];
            if (message.mentions.members.size == 1) {
                receiver = message.mentions.members.first().user;
            } else {
                receiver = await bot.fetchUser(args[0]);
            }

            var keyType = null;
            var keyInfos = null;
            if (args[1] == 'boost') {
                keyType = args[2] == 'xp' ? 'XP Boost' : 'Gold Boost';
                const boostData = {
                    type: args[2],
                    boost: args[3],
                    duration: args[4],
                    expiration: args[5] != null ? args[5] : '0'
                }
                keyInfos = `**${args[4]}** of **${boostData.boost}%**${boostData.expiration == 0 ? '': `, expiring in **${boostData.expiration}**`}.`;
                await poolQuery(`INSERT INTO codes (keygen, type, data) VALUES ('${key}', 'boost', '${JSON.stringify(boostData)}')`);
            } else if (args[1] == 'item') {

            } else if (args[1] == 'ether') {
                
            } else if (args[1] == 'xp') {
                
            } else {
                message.channel.send(`There is a problem with your args, **${message.author.username}**.`);
            }

            const embed = new Discord.RichEmbed()
                .setTitle('Key Generated')
                .setDescription(`To use your key, type **${config.app.prefix}redeem [KEY]**.\n**Key** : ${key}\n**Type** : ${keyType}\n**Informations** : ${keyInfos}`)
                .setColor('BLUE')
                .setFooter(`Code Generated by ${message.author.username}`, message.author.avatarURL);
            receiver.send({embed});
            message.channel.send(`The key has been sent to the private messages of **${receiver.username}**.`);
        } else {
            message.channel.send(`There is a problem with your args, **${message.author.username}**.`);
        }
    } else {
        message.channel.send(`You need to be part of the development team of Tranquility to execute this command, **${message.author.username}**.`);
    }
}